version: "3.9"

services:

    client:
      container_name: prakticum-client
      image: prakticum-client
      build:
        context: .
        dockerfile: Dockerfile.client
        args:
          CLIENT_PORT: 3000
      ports:
        - "3000:3000"
      environment:
        - CLIENT_PORT=3000
        - SERVER_PORT=3001
        - SERVER_HOST=localhost
      restart: always
