version: "3.9"

services:
    postgres:
      image: postgres:14
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      restart: always
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      networks:
        - awesome

    client:
      container_name: prakticum-client
      image: prakticum-client
      build:
        context: .
        dockerfile: Dockerfile.client
        args:
          CLIENT_PORT: 3000
      ports:
        - "3000:3000"
      environment:
        - CLIENT_PORT=3000
        - SERVER_PORT=3001
        - SERVER_HOST=localhost
      restart: always
      networks:
        - awesome

    server:
      container_name: prakticum-server
      image: prackicum-server
      build:
        context: .
        dockerfile: Dockerfile.server
        args:
          SERVER_PORT: 3001
      ports:
        - "3001:3001"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        POSTGRES_PORT: 5432
        POSTGRES_HOST: postgres
        SERVER_PORT: 3001
        NODE_ENV: production
      networks:
        - awesome
      volumes:
        - ./packages/client/dist:/app/client/dist
        - ./packages/client/dist-ssr:/app/client/dist-ssr
      depends_on:
        - postgres
        - client
      command: >
        sh -c "/app/wait-for.sh postgres:5432 -- node /app/index.js"

networks:
  awesome:
    driver: bridge
