FROM node:$NODE_VERSION-buster-slim as production

WORKDIR /app


COPY --from=builder /app/packages/client/dist /app/dist


RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
