version: "3.9"

services:
    postgres:
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      restart: always
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      networks:
        - awesome
    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4:4.18
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "${PGADMIN_PORT}:80"
      volumes:
        - ./tmp/pgadmin-data:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - awesome

networks:
  awesome:
    driver: bridge

